### PR TITLE
Unignore flake8 E123, E126, E305, E741, W504.  <#3666>

### PR DESCRIPTION
**Pull request by arogl**
## Description

Unignore flake8 E123, E126, E305, E741, W504.  <#3666>

## To Do

- [X] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [ ] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)
- [X] Tests. (Encouraged but not strictly required.)

### CODE REVIEW

**Comment by jtpavlock** [comment]
Yo! I think it would actually be better to just target upstream at beetbox/beets so the team there can get eyes on it. Just mention it's based off/intended to succeed my pr

**Comment by jtpavlock** [comment]
Also, if you want to clean up the commits, it would make sense to just do a soft reset and squash those into a single commit. Would make even more sense to split each error message into it's own commit to be able to clearly see the impact of un-ignoring each, but I realize that may be a bit more work 😄

**Comment by arogl** [comment]
I'll look into this after work today.

Do I pull you request into my branch or do I recreate your commits?

**Comment by jtpavlock** [comment]
best is probably to rebase it off mine

**Comment by arogl** [comment]
> 
> 
> best is probably to rebase it off mine

Some reading to catch up on git usage :-)

**Comment by jtpavlock** [comment]
I'm by no means an expert, but feel free to ask questions if they come up

**Comment by arogl** [comment]
> 
> 
> I'm by no means an expert, but feel free to ask questions if they come up

I might 
git clone beetbox\beets
git create/checkout branch flake8-feature
The bit I don't understand, do I pull your PR for the change or just apply your diff into my branch? - I would like credit you for the original changes.
Fix Exxx unignore whitespace
Commit Exxx unignore whitespace
cycle through the above 2 until all done
Commit and Push to Origin

**Comment by jtpavlock** [comment]
It definitely is tricky since you're dealing with 3 different repositories haha. 

So, what you would do is 

1. Add my repository as a remote
`git remote add jtpavlock/beets git@github.com:jtpavlock/beets.git`
2. Fetch my branch
`git fetch jtpavlock/beets`
3. Now, depending on what you're trying to do, you have some options.
    a. At this point, if you are starting a new branch, you could just checkout my `flake8-errors` branch and then create your own off of it. So, something like,
`git checkout remotes/jtpavlock/flake8-errors` (verify that branch name is correct with `git branch -a`
`git checkout -b <arogl_branch>`
    b. If you want to keep an existing branch and incorporate my changes, the easiest way to do that is probably to rebase it
`git checkout <arogl_branch`
`git rebase remotes/jtpavlock/flake8-errors`
    c. I think merging as you suggested would be another option here
4. Then, as you suggested you do one error at a time making a commit for each.
5. Finally, once your done, you should be able to push to your origin and make a pull request to beetbox/beets through github

Again, I'm not an expert, but I believe that's the general idea

**Comment by jtpavlock** [comment]
To be honest, you could also just make a pull request straight to github. You don't necessarily need my changes except my changes to `setup.cfg` (I kind of made this whole thing more complicated by changing that... whoops). 

Once my branch gets merged to beetbox/beets, you would then just have to fix a merge conflict.

Like I said, lots of ways to tackle this

**Comment by arogl** [comment]
Had another attempt on beetbox/beets
[Unignore flake8 E123, E126, E305, E741, W504](https://github.com/beetbox/beets/pull/3669)

**Pull request closed without merging**
